CREATE TABLE t_kb_quality_issue (
    id BIGINT NOT NULL AUTO_INCREMENT,
    issue_id VARCHAR(64) NOT NULL,
    kb_id VARCHAR(64) NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    source_id VARCHAR(64) NOT NULL,
    source_doc_id VARCHAR(64) NULL,
    protected_doc_ids MEDIUMTEXT NULL,
    summary VARCHAR(1024) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'NEW',
    owner_user_id VARCHAR(64) NULL,
    owner_name VARCHAR(128) NULL,
    reason VARCHAR(32) NULL,
    dataset_id VARCHAR(64) NULL,
    case_id VARCHAR(64) NULL,
    expected_case_input MEDIUMTEXT NULL,
    affected_app_version_id VARCHAR(64) NULL,
    verified_run_id VARCHAR(64) NULL,
    verified_app_version_id VARCHAR(64) NULL,
    resolved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    lock_version INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_quality_issue_id (issue_id),
    UNIQUE KEY uk_quality_issue_source (kb_id, source_type, source_id),
    KEY idx_quality_issue_status (kb_id, status, id),
    KEY idx_quality_issue_owner (kb_id, owner_user_id, id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '知识质量问题及已确认纠正用例';

CREATE TABLE t_kb_quality_issue_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    issue_id VARCHAR(64) NOT NULL,
    actor_user_id VARCHAR(64) NOT NULL,
    actor_name VARCHAR(128) NOT NULL,
    action VARCHAR(32) NOT NULL,
    note VARCHAR(2048) NULL,
    case_id VARCHAR(64) NULL,
    run_id VARCHAR(64) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    lock_version INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_quality_issue_record (issue_id, id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '知识质量问题处理记录';
